---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo
  namespace: test
  labels:
    k8s-app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: demo
  template:
    metadata:
      name: demo
      labels:
        k8s-app: demo
    spec:
      containers:
        - name: demo
          image: 'flowkap/goodbye:latest'
          imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: demo
  namespace: test
  labels:
    k8s-app: demo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: demo
  type: ClusterIP
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: demo
  namespace: test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/flowkap)$ $1/ permanent;
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: dev.cip.swarco.com
      http:
        paths:
          - path: /flowkap/?(.*)
            backend:
              serviceName: demo
              servicePort: 80
